name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # INTRODUCTION
          plugin_introduction: yes
          plugin_introduction_title: yes

          # LANGUAGES
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_ignored: glsl

          # REPOSITORIES
          plugin_repositories: yes
          plugin_repositories_featured: osww, winderoo, pf2opn, YouTubePlays-vs-TwitchPlays
          plugin_repositories_order: featured

          # ACHIEVEMENTS
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_limit: 6
